[tool.black]
line-length = 88
target-version = ['py310']

profile = "black"
line_length = 88
known_first_party = ["src", "tests"]
skip = ["venv", ".git", "__pycache__"]

[tool.mypy]
explicit_package_bases = true
plugins = sqlalchemy.ext.mypy.plugin
