# .github/workflows/code_quality.yml
name: Code Quality and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy pytest pytest-cov sqlalchemy fastapi uvicorn

      - name: Run isort check
        run: isort --check --profile black .

      - name: Run black check
        run: black --check .

      - name: Run flake8 lint
        run: flake8 .

      - name: Run mypy type check
        run: mypy .

      - name: Run tests with pytest and coverage
        run: pytest .
